### ISSUE TITLE
Спорное решение - на каждый метод создавать новый сервис и репозиторий

### ISSUE THREAD

**Issue by coursar** [Daaamir2/PropertySearch#3]
https://github.com/Daaamir2/PropertySearch/blob/f8061cd2c7f6e83d9f15cfcd797d521c14111b7b/src/ru/itpark/Main.java#L35

Если репозиторий будет открывать подключение к БД, то попадёте на `too many connections`

**Comment by Daaamir2** [comment]
81efb182885a9f734814cc1f6df4c4e121c2116e Исправил

**Comment by Daaamir2** [comment]
Исправил
