### ISSUE TITLE
Что будет, если в первом try у вас сработает Exception?

### ISSUE THREAD

**Issue by coursar** [Daaamir2/PropertySearch#6]
https://github.com/Daaamir2/PropertySearch/blob/81efb182885a9f734814cc1f6df4c4e121c2116e/src/main/java/ru/itpark/comparator/DateDecComparator.java#L18-L28

**Comment by Daaamir2** [comment]
Я так понимаю, что выйдет stackTrace с ошибкой и до второго try исполнение кода уже не дойдет.

**Comment by Daaamir2** [comment]
Можно ли объединить и сделать один блок try catch? ad2a7be414605bf4279dbc389c89a9020ecec49a

**Comment by coursar** [comment]
можно

**Comment by coursar** [comment]
а лучше всё завернуть в try
