### ISSUE TITLE
Зачем конструктор, если @AllArgsConstructor?

### ISSUE THREAD

**Issue by coursar** [Daaamir2/PropertySearch#9]
https://github.com/Daaamir2/PropertySearch/blob/b8a6bfb85e134d4e5517e2e3b234b8a247828ac3/src/main/java/ru/itpark/domain/House.java#L18-L26

**Comment by Daaamir2** [comment]
Я не знал как сделать конструктор без одного параметра (metro), поэтому решил написать его.

**Comment by Daaamir2** [comment]
Исправил при помощи @RequiredArgsConstructor, можно ли так делать?
